import os
from supabase import create_client, Client
from dotenv import load_dotenv

load_dotenv()

url = os.environ.get("SUPABASE_URL")
key = os.environ.get("SUPABASE_KEY")
supabase: Client = create_client(url, key)

def setup_table():
    print("⏳ Setting up Supabase table...")
    # SQL to create the table
    # Note: supabase-py doesn't have a direct 'execute_sql' for anon keys.
    # The user should ideally run this in the Supabase SQL Editor.
    # But we can try to verify if the table exists by doing a simple select.
    try:
        response = supabase.table("food_events").select("*").limit(1).execute()
        print("✅ Table 'food_events' already exists and is accessible.")
    except Exception as e:
        print("❌ Could not access 'food_events' table.")
        print("Please ensure you have run the following SQL in your Supabase SQL Editor:")
        print("""
CREATE TABLE IF NOT EXISTS food_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    source TEXT,
    source_handle TEXT,
    post_id TEXT UNIQUE,
    club_name TEXT,
    event_name TEXT,
    date TEXT,
    time TEXT,
    location TEXT,
    food_provided TEXT,
    has_free_food BOOLEAN,
    food_rank INTEGER,
    confidence_score FLOAT,
    image_path TEXT,
    status TEXT DEFAULT 'PENDING'
);

-- Enable RLS
ALTER TABLE food_events ENABLE ROW LEVEL SECURITY;

-- Create policy to allow anyone to read
CREATE POLICY "Allow public read access" ON food_events FOR SELECT USING (true);
        """)

if __name__ == "__main__":
    setup_table()
